module.exports = {
  apps: [
    {
      name: 'support-mcp-server',
      script: 'dist/index.js',
      cwd: '/var/www/whatsapp-bot-builder/support-mcp-server',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/support-mcp-server-error.log',
      out_file: '/var/log/pm2/support-mcp-server-out.log',
      log_file: '/var/log/pm2/support-mcp-server.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        LOG_LEVEL: 'info',
    SUPABASE_REALTIME_DEBUG: 'true',
      },
    },
    {
      name: 'file-writer-worker',
      script: 'dist/workers/fileWriterWorker.js',
      cwd: '/var/www/whatsapp-bot-builder/support-mcp-server',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      error_file: '/var/log/pm2/file-writer-worker-error.log',
      out_file: '/var/log/pm2/file-writer-worker-out.log',
      log_file: '/var/log/pm2/file-writer-worker.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        LOG_LEVEL: 'info',
        FILE_WRITER_PORT: '3003',
      },
    },
  ],
};
